name: Minkabu Scraper Schedule

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行（1時間ごと）

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v3

    - name: Node.jsセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 依存パッケージをインストール
      run: npm install

    - name: スクレイピング実行
      run: node index.js
